spring:
  config:
    activate:
      on-profile: prod

build:
  version: "1.0"

loans:
  message: "Welcome to the Loans Service related to prod api"
  contactDetails:
    name: "John Doe - Product Owner"
    email: "prod@gmail.com"
  onCallSupport:
    -(777) 555-1234
    -(777) 555-5678
