logging:
  level:
    com.eazybytes.cards.controller: DEBUG
server:
  port: 9000
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_prod.yml"
      - "application_qa.yml"

  profiles:
    active:
      - "qa"

build:
  version: "3.0"

cards:
  message: "Welcome to the Accounts Service"
  contactDetails:
    name: "Saurav Bhasin - Developer"
    email: "test@gmail.com"
  onCallSupport:
    -(555) 555-1234
    -(555) 555-5678
