spring:
  config:
    activate:
      on-profile: qa

build:
  version: "2.0"

cards:
  message: "Welcome to the Cards Service related to QA"
  contactDetails:
    name: "John Doe - QA"
    email: "qa@gmail.com"
  onCallSupport:
    -(666) 555-1234
    -(666) 555-5678
