
build:
  version: "2.0"

accounts:
  message: "Welcome to the Accounts Service related to QA"
  contactDetails:
    name: "John Doe - QA"
    email: "qa@gmail.com"
  onCallSupport:
    -(666) 555-1234
    -(666) 555-5678
