build:
  version: "3.0"

accounts:
  message: "Welcome to the Accounts Service"
  contactDetails:
    name: "Saurav Bhasin - Developer"
    email: "test@gmail.com"
  onCallSupport:
    -(555) 555-1234
    -(555) 555-5678
