build:
  version: "1.0"

cards:
  message: "Welcome to the Cards Service related to prod api"
  contactDetails:
    name: "John Doe - Product Owner"
    email: "prod@gmail.com"
  onCallSupport:
    -(777) 555-1234
    -(777) 555-5678
